const express = require('express');
const fileRoute = express.Router();
const { uploadFileController, upload } = require('../controllers/file/uploadFileController');
// const readFilesController = require('../controllers/file/readFilesController');
const readFilesController = require('../controllers/file/readFilesController');
const readVideosController = require('../controllers/file/readVideosController');
const readDocumentsController = require('../controllers/file/readDocumentsController');
const readImageS3Controller = require('../controllers/file/readImageS3Controller');
const folderHierarchy = require('../middleware/folder/folderHierarchy');
const pasteFileController = require("../controllers/file/pasteFileController");
const fileUploadInitiateController = require('../controllers/file/fileUploadInitiateController');
const getPresignedURLController = require('../controllers/file/getPre-signedURLController');
const getPresignedFileURLController = require('../controllers/file/getPre-signedFileURLController');
const fileChunksAssemblyController = require('../controllers/file/fileChunksAssemblyController');
const sessionUploadPartsController = require('../controllers/file/sessionUploadPartsController');
const fileResumeInitiateController = require('../controllers/file/fileResumeInitiateController');
const multipartUploadFileController = require('../controllers/file/multipartUploadFileController');
const renameFileController = require('../controllers/file/renameFileController');
const fileMultipartUpload = require('../controllers/file/fileMultipartUpload');
const systemCancelMultipartUploadController = require('../controllers/file/systemCancelMultipartUploadController');
const systemCancelFileUploadController = require('../controllers/file/systemCancelFileUploadController');
const checkFileDuplicateController = require('../controllers/file/checkFileDuplicateController');
const fileRenameController = require('../controllers/Rename/fileRenameController');
const apiAuth = require('../middleware/auth/authMiddleware');

fileRoute.post('/uploadfile', upload.single('file'), apiAuth, folderHierarchy, uploadFileController, fileUploadInitiateController);
fileRoute.post('/pastefile', apiAuth, pasteFileController);
// fileRoute.get('/files/:userID', readFilesController);
fileRoute.get('/files', apiAuth, readFilesController);
fileRoute.get('/file/:fileID', getPresignedFileURLController);
fileRoute.get('/files/videos/:userID', apiAuth, readVideosController);
fileRoute.get('/files/documents/:userID', apiAuth, readDocumentsController);
fileRoute.get('/file/image', readImageS3Controller);
// fileRoute.post('/file/upload/initiate', fileUploadInitiateController);
fileRoute.get('/file/upload/url', getPresignedURLController);
fileRoute.post('/file/upload/complete', apiAuth, fileChunksAssemblyController);
fileRoute.post('/file/uploadsession/uploadparts', apiAuth, sessionUploadPartsController);
fileRoute.post('/file/resume/initiate', apiAuth, fileResumeInitiateController);
fileRoute.post('/uploadfile/initiate', apiAuth, multipartUploadFileController, fileUploadInitiateController);
fileRoute.post('/file/rename', apiAuth, renameFileController);
fileRoute.put('/file/:fileID', apiAuth, systemCancelMultipartUploadController, systemCancelFileUploadController);
fileRoute.post('/file/checkduplicatefiles', apiAuth, checkFileDuplicateController);
fileRoute.patch('/file/fileRename', apiAuth, fileRenameController);

module.exports = fileRoute;
