const express = require('express');
const fileRoute = express.Router();
const { uploadFileController, upload } = require('../controllers/file/uploadFileController');
const readFilesController = require('../controllers/file/readFilesController');
const readImagesController = require('../controllers/file/readImagesController');
const readVideosController = require('../controllers/file/readVideosController');
const readDocumentsController = require('../controllers/file/readDocumentsController');
const readImageS3Controller = require('../controllers/file/readImageS3Controller');
const folderHierarchy = require('../middleware/folder/folderHierarchy');
const pasteFileController = require("../controllers/file/pasteFileController");
const fileUploadInitiateController = require('../controllers/file/fileUploadInitiateController');
const getPresignedURLController = require('../controllers/file/getPre-signedURLController');
const fileChunksAssemblyController = require('../controllers/file/fileChunksAssemblyController');
const sessionUploadPartsController = require('../controllers/file/sessionUploadPartsController');
const fileResumeInitiateController = require('../controllers/file/fileResumeInitiateController');
const multipartUploadFileController = require('../controllers/file/multipartUploadFileController');

fileRoute.post('/uploadfile', upload.single('file'), folderHierarchy, uploadFileController, fileUploadInitiateController);
fileRoute.post('/pastefile', folderHierarchy, pasteFileController);
// fileRoute.get('/files/:userID', readFilesController);
fileRoute.get('/files/images', readImagesController);
fileRoute.get('/files/videos/:userID', readVideosController);
fileRoute.get('/files/documents/:userID', readDocumentsController);
fileRoute.get('/file/image', readImageS3Controller);
// fileRoute.post('/file/upload/initiate', fileUploadInitiateController);
fileRoute.get('/file/upload/url', getPresignedURLController);
fileRoute.post('/file/upload/complete', fileChunksAssemblyController);
fileRoute.post('/file/uploadsession/uploadparts', sessionUploadPartsController);
fileRoute.post('/file/resume/initiate', fileResumeInitiateController);
fileRoute.post('/uploadfile/initiate', multipartUploadFileController, fileUploadInitiateController);

module.exports = fileRoute;
